export const selections = [
  {
    deployment: 2808,
    period_start: new Date('2023-12-19'),
    period_end: new Date('2024-03-14'),
    title: 'Wagon Center',
    title_de: 'Cargo-Wagen im Zentrum',
    group: 'Dreispitz',
    framerate: 2,
    interval: undefined,
    phase: 'night',
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 1215,
    period_start: new Date('2023-05-04'),
    period_end: new Date('2023-11-17'),
    title: 'Gleishof',
    title_de: 'Gleishof',
    group: 'Dreispitz',
    framerate: 2,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 1901,
    period_start: new Date('2023-07-05'),
    period_end: new Date('2023-08-22'),
    title: 'Wagon Periphery 1',
    title_de: 'Cargo-Wagen Richtung Bruderholz 1',
    group: 'Dreispitz',
    framerate: 2,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 1901,
    period_start: new Date('2023-08-23'),
    period_end: new Date('2023-11-03'),
    title: 'Wagon Periphery 2',
    title_de: 'Cargo-Wagen Richtung Bruderholz 2',
    group: 'Dreispitz',
    framerate: 2,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 1901,
    period_start: new Date('2023-11-03'),
    period_end: new Date('2024-03-15'),
    title: 'Wagon Periphery 3',
    title_de: 'Cargo-Wagen Richtung Bruderholz 3',
    group: 'Dreispitz',
    framerate: 5,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 1132,
    period_start: new Date('2023-04-25'),
    period_end: new Date('2023-05-12'),
    title: 'Foxhole',
    title_de: 'Fuchsbau',
    group: 'Reinacher Heide',
    framerate: 2,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 273,
    period_start: new Date('2022-12-09'),
    period_end: new Date('2024-06-01'),
    title: 'Beaver Slide',
    title_de: 'Biber-Rutsche',
    group: 'Reinacher Heide',
    framerate: 1,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 1072,
    period_start: new Date('2023-02-14'),
    period_end: new Date('2023-04-24'),
    title: 'Dry Grassland 1',
    title_de: 'Trockenwiese',
    group: 'Reinacher Heide',
    framerate: 1,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 974,
    period_start: new Date('2023-04-26'),
    period_end: new Date('2023-06-28'),
    title: 'Village Creek',
    title_de: 'Dorfbach',
    group: 'Reinacher Heide',
    framerate: 1,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 3154,
    period_start: new Date('2017-03-18'),
    period_end: new Date('2017-03-27'),
    title: 'Channel Island 1',
    title_de: 'Birs-Kanalinsel 1',
    group: 'Merian Gärten',
    framerate: 0.5,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 3171,
    period_start: new Date('2019-07-24'),
    period_end: new Date('2019-09-13'),
    title: 'Channel Island 2',
    title_de: 'Birs-Kanalinsel 2',
    group: 'Merian Gärten',
    framerate: 0.5,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 3188,
    period_start: new Date('2020-09-23'),
    period_end: new Date('2020-10-25'),
    title: 'Channel Island 3',
    title_de: 'Birs-Kanalinsel 3',
    group: 'Merian Gärten',
    framerate: 0.5,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 883,
    period_start: new Date('2023-04-21'),
    period_end: new Date('2023-06-24'),
    title: 'Pollinator Flowerpot 1',
    title_de: 'Blumentopf einer Bestäuber-Installation',
    group: 'Merian Gärten',
    framerate: 1,
    interval: 3600,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 24,
    period_start: new Date('2022-05-12'),
    period_end: new Date('2022-08-09'),
    title: 'Pollinator Flowerpot 2',
    title_de: 'Blumentopf einer Bestäuber-Installation',
    group: 'Merian Gärten',
    framerate: 1,
    interval: 3600,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },

  {
    deployment: 24,
    period_start: new Date('2022-08-12'),
    period_end: new Date('2022-08-28'),
    title: 'Bike Parking Roof',
    title_de: 'Veloparking-Dach',
    group: 'Dreispitz',
    framerate: 1,
    interval: 3600,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 67,
    period_start: new Date('2022-08-15'),
    period_end: new Date('2022-08-28'),
    title: 'Closed Railway Tracks',
    title_de: 'Güterverkehr-Gleise',
    group: 'Dreispitz',
    framerate: 1,
    interval: 3600,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 820,
    period_start: new Date('2023-04-04'),
    period_end: new Date('2023-09-07'),
    title: 'Discovery Pond 1',
    title_de: 'Erlebnisweiher 1',
    group: 'Reinacher Heide',
    framerate: 2,
    interval: 24*3600,
    phase: undefined,
    landscape: false,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 829,
    period_start: new Date('2023-04-04'),
    period_end: new Date('2023-06-26'),
    title: 'Discovery Pond 2',
    title_de: 'Erlebnisweiher 2',
    group: 'Reinacher Heide',
    framerate: 2,
    interval: 24*3600,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 824,
    period_start: new Date('2023-04-04'),
    period_end: new Date('2023-07-19'),
    title: 'Dry Grassland 2',
    title_de: 'Trockenwiese 2',
    group: 'Reinacher Heide',
    framerate: 2,
    interval: 24*3600,
    phase: undefined,
    landscape: false,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 1184,
    period_start: new Date('2023-04-25'),
    period_end: new Date('2023-06-27'),
    title: 'Dry Grassland 3',
    title_de: 'Trockenwiese 3',
    group: 'Reinacher Heide',
    framerate: 1,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 1880,
    period_start: new Date('2023-07-05'),
    period_end: new Date('2023-07-08'),
    title: 'Wagon Center 2',
    title_de: 'Cargowagen InsektenKiosk',
    group: 'Dreispitz',
    framerate: 1,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 202,
    period_start: new Date('2022-12-12'),
    period_end: new Date('2022-12-29'),
    title: 'Wild Crossing 1',
    title_de: 'Wildwechsel 1',
    group: 'Reinacher Heide',
    framerate: 1,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 344,
    period_start: new Date('2023-01-09'),
    period_end: new Date('2023-02-13'),
    title: 'Wild Crossing 2',
    title_de: 'Wildwechsel 2',
    group: 'Reinacher Heide',
    framerate: 1,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 3203,
    period_start: new Date('2022-07-22'),
    period_end: new Date('2022-07-23'),
    title: 'Lizzards',
    title_de: 'Eidechsen',
    group: 'Dreispitz',
    framerate: 10,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
  {
    deployment: 2882,
    period_start: new Date('2022-03-23'),
    period_end: new Date('2022-03-23'),
    title: 'Lizzards',
    title_de: 'Eidgechsen',
    group: 'Merian Gärten',
    framerate: 10,
    interval: undefined,
    phase: undefined,
    landscape: true,
    phases: [
      { phase_start: 0, phase_end: 24 },
    ],
  },
];
